/**
 * app-assets.ts — every lucide icon and every image the app uses, for the debug
 * sandbox's Icons and Images sections (maintainer, 2026-10-08). `app-assets.test.ts`
 * scans src/ and public/ and fails until a new icon or image is listed here, so the
 * sandbox cannot fall behind the app again. Debug-only: nothing here reaches an LO page.
 */
import {
  ArrowDownAZ,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpZA,
  BookOpenIcon,
  Check,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CircleX,
  Eye,
  EyeOff,
  ExternalLink,
  Frown,
  Info,
  Layers,
  Lightbulb,
  Menu,
  MoonIcon,
  PanelLeftIcon,
  RotateCcw,
  Smile,
  SunIcon,
  Volume2,
  XIcon,
  type LucideIcon,
} from 'lucide-react';

/** Lucide icons by the name the code imports them under. */
export const APP_ICONS: Readonly<Record<string, LucideIcon>> = {
  ArrowDownAZ,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpZA,
  BookOpenIcon,
  Check,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CircleX,
  Eye,
  EyeOff,
  ExternalLink,
  Frown,
  Info,
  Layers,
  Lightbulb,
  Menu,
  MoonIcon,
  PanelLeftIcon,
  RotateCcw,
  Smile,
  SunIcon,
  Volume2,
  XIcon,
};

/** Every image under public/ (paths relative to it), the sprite aside. */
export const APP_IMAGES: readonly string[] = [
  'favicon.svg',
  'logo.svg',
  'images/lo-placeholder.svg',
  'images/placeholders/reading.svg',
  'images/lo-00-example/hero.svg',
  'images/lo-00-example/03-outcomes/illustration.svg',
  'images/lo-00-example/04-tabs/chart.svg',
  'images/lo-00-example/04-tabs/speaker.svg',
  'images/lo-00-example/06-intro/illustration.svg',
  'images/lo-00-example/07-intro/illustration.svg',
  'images/line-match/circle.svg',
  'images/line-match/square.svg',
  'images/line-match/star.svg',
  'images/line-match/triangle.svg',
  'images/footer/cc-logo-black.svg',
  'images/footer/cc-logo-white.svg',
  'images/footer/elearning-logo-black.svg',
  'images/footer/elearning-logo-white.svg',
  'images/footer/lc-logo-black.svg',
  'images/footer/lc-logo-white.svg',
  'images/footer/ucam-lockup-dark.png',
  'images/footer/ucam-lockup-light.png',
];
